### ISSUE TITLE
Doubt about tests

### ISSUE THREAD

**Issue by marcelinhov2** [vandium-io/lambda-tester#29]
Hey guys, first of all, congratulations for your project, it's awesome.

I have this function:
```js
exports.handler = function(event, context, callback) {
  const processor = require('./src/processor');

  return processor(event)
    .then( function(res) {
      callback(null, res);
    } );
};
```

```processor``` is a promise, but I don't know how to mock it response to run my unit test. It's giving me a Timeout everitime it runs. Can you guys help me with this?

Thanks a lot.

**Comment by richardhyatt** [comment]
I would suggest re-writing so that the error condition is caught:

```js
const processor = require('./src/processor');

exports.handler = function(event, context, callback) {

  processor(event)
    .then( (res) => {
      callback(null, res);
    })
    .catch( (err) => {
      callback( err );
    });
};
```

Now if `processor()` throws an exception via the `reject` mechanism, your handler will catch it an invoke `callback()` properly, thus not entering into the timeout state.

If you're interested, check out our [vandium](https://github.com/vandium-io/vandium-node) project that greatly simplifies writing Lambda handlers and supports promises, performs validation, and helps improve the security of the code.

As for mocking the `processor`, I prefer to use [proxyquire](https://github.com/thlorenz/proxyquire).

Let us know if this helps.

**Comment by richardhyatt** [comment]
Can we close this issue?

**Comment by marcelinhov2** [comment]
Thanks for you reply and sorry for the delay, I didn't saw the email notification. I'll try to implement your solution.

If I need any other help, I reopen the issue.

Thanks again. :)
