### ISSUE TITLE
package engines requirement for node v6.x.x is incorrect.

### ISSUE THREAD

**Issue by stevenao** [vandium-io/lambda-tester#38]
https://github.com/vandium-io/lambda-tester/blob/master/package.json#L23

Looks like a syntax error there. I am using node v6.13.0 and npm keeps failing saying incompatible node engine version. It works fine only if I switch to node v8.x.x (8.9.0 in my machine).

**Comment by stevenao** [comment]
I think in v3.3.0, you had `"node": ">=6.0.0 <7.0.0"`. It looks like your library works for 7.x.x too. Can you use `"node": ">=6.0.0 <=8.0.0"`?

**Comment by kaxelson** [comment]
I think the problem here is the comma.  You have "node": "^6.0.0, ^8.0.0".  If you change to "node": "^6.0.0 ^8.0.0", it works.  FYI, I'm using yarn which uses semver under the covers to validate the range.  semver does not work with the comma.

r = new semver.Range("^6.0.0, ^8.0.0", true)
Range {
  loose: true,
  raw: '^6.0.0, ^8.0.0',
  set: [ [ [Object], [Object] ] ],
  range: '>=8.0.0 <9.0.0' }

r = new semver.Range("^6.0.0 ^8.0.0", true)
Range {
  loose: true,
  raw: '^6.0.0 ^8.0.0',
  set: [ [ [Object], [Object], [Object], [Object] ] ],
  range: '>=6.0.0 <7.0.0 >=8.0.0 <9.0.0' }

**Comment by richardhyatt** [comment]
Resolved in 3.4.1

**Comment by jimedelstein** [comment]
@richardhyatt doesn't look like official npm registry was updated to 3.4.1
