### ISSUE TITLE
Print additional information on promise errors

### ISSUE THREAD

**Issue by undsoft** [vandium-io/lambda-tester#49]
Not sure if this is the problem with lambda-tester/jest or nodejs.

I'm trying to do TDD with lambda tester and thus my code fails a lot.
However, quite often I don't see the information about what went wrong.

I just get
> Promise.reject() called instead of Promise.resolve()
>   at processOutcome (../../node_modules/lambda-tester/lib/runner.js:57:15)
>       at Promise.resolve.then.then.then (../../node_modules/lambda-tester/lib/runner.js:277:26)

Is there a way to also print the error from reject?

**Comment by edbo** [comment]
Yeah I'm wondering if this is intended behavior too?

I've made a commit here that restores the original error stack. It's caused because when FailError is invoked the stack of FailError is used by testing tools like mocha rather than the real error created by the promise rejection.

https://github.com/edbo/lambda-tester/commit/80e6a93fbe842fe3a34f5b63c32f14541eb848d4

I'm not going to make a pull request as of yet because a change like this could break functionality rather this is a discussion point for what is desirable.

**Comment by edbo** [comment]
@richardhyatt Wondering if you can comment on this?

**Comment by richardhyatt** [comment]
I think the change would be fine - can you create a pull request for the change and additional unit tests. Thanks
