### ISSUE TITLE
Support Node v12

### ISSUE THREAD

**Issue by munierujp** [vandium-io/lambda-tester#54]
AWS Lambda now supports Node v12 :tada:

cf. [AWS Lambda now supports Node.js 12](https://aws.amazon.com/jp/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/)

**Comment by jkehres** [comment]
Addressed by #55. Just waiting on a new version of the library to be published to npm.

**Comment by munierujp** [comment]
Thanks, it will be resolved by #55

**Comment by richardhyatt** [comment]
It will be part of the 4.0 release - see the 4.x branch

**Comment by jkehres** [comment]
@richardhyatt Not to be pushy or anything but do you have an approximate ETA for the 4.0 release (e.g. days, weeks, or months away)? AWS is EOL'ing Node 8 at the end of the year and I'm looking to upgrade a number of my lambdas to Node 12. The tests for these lambdas all use `lambda-tester` so I'm blocked from completing my upgrade until I can get a version of this library that supports Node 12.

**Comment by richardhyatt** [comment]
Looking to get it pushed out shortly - I require it for one of my own projects. In version 4.0, and forwards, version checking will be disabled because AWS seems to be staying a little more current than it had when lambda was first launched.

You can always disable version checking by setting the environment variable `LAMBDA_TESTER_NODE_VERSION_CHECK=false`

**Comment by jkehres** [comment]
Awesome, thanks! Also, I didn't know about `LAMBDA_TESTER_NODE_VERSION_CHECK`. Thanks for the pro-tip.
